name: testworks
on:
  workflow_dispatch:
    inputs:
      enable_feature_kpm:
        description: 'KPM'
        required: false
        default: true
        type: boolean
      enable_feature_bbr:
        description: 'BBR'
        required: false
        default: true
        type: boolean
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 测试
        run: |
